release: v0.0.1
Devleaps/github-secret-synchronizer pull request #1
Opened 2024-09-20 14:14 UTC by tijmenstor

2024-09-20 14:36 UTC, Netail commented on .gitignore
> +# that are supposed to be shared within teams.
Excessive comments

2024-09-20 14:40 UTC, LucasGeisink commented on .goreleaser.yaml
> +    <a href="https://argoproj.github.io/cd/"><img src="https://raw.githubusercontent.com/argoproj/argo-site/master/content/pages/cd/gitops-cd.png" width="25%" ></a>
hardcoded?

2024-09-20 15:10 UTC, NielsMoorenAH reviewed
You can build the Go program without going in another directory. This also makes the CMD command cleaner and leaner

2024-09-20 15:10 UTC, NielsMoorenAH commented on Dockerfile
> +RUN CGO_ENABLED=0 GOOS=linux go build -o /github-secrets-synchronizer/github-secrets-synchronizer
```suggestion
RUN CGO_ENABLED=0 GOOS=linux go build -o /github-secrets-synchronizer
```

2024-09-20 15:10 UTC, NielsMoorenAH commented on Dockerfile
> +CMD ["/github-secrets-synchronizer/github-secrets-synchronizer"]
```suggestion
CMD ["/github-secrets-synchronizer"]
```

2024-09-20 15:50 UTC, DatIsNiels approved these changes

2024-09-20 15:50 UTC, DatIsNiels commented
Yeet

2024-09-20 20:39 UTC, ma-ts requested changes
Do not see the added value of this PR

2024-09-20 20:47 UTC, tsoetje requested changes

2024-09-20 20:47 UTC, tsoetje commented on internal/github/github.go
> +// Client defines the interface for interacting with GitHub
What in the copilot is this, does not add anything. It is in the GitHub file and already a client interface

2024-09-20 20:47 UTC, tsoetje commented on internal/github/github.go
> +// GitHubService implements the Client interface
Same

2025-01-03 14:15 UTC, Netail requested changes

2025-01-03 14:15 UTC, Netail commented on LICENSE
> +   Copyright [yyyy] [name of copyright owner]
```suggestion
   Copyright 2025 Devleaps
```

2025-01-03 23:10 UTC, tsoetje commented on .github/workflows/publish.yaml
> +  goreleaser:
```suggestion
  release:
```
gorelease is being used but the job is creating a release. So this is more clear imo

2025-01-03 23:10 UTC, tsoetje commented on README.md
> +- `repositories` (string) **optional**: The repositories that the secret/variable should be visible to (comma-separated)
Since these are optional they probably have a default behaviour? Could you add the default value/behaviour when not set

2025-01-03 23:10 UTC, tsoetje commented on README.md
> +To set the necessary environment variables to be able to run github-secrets-synchronizer locally, you can create a `.env` file in the root of the project.
would be nice to have a .env.example

2025-01-03 23:10 UTC, tsoetje commented on internal/github/github.go
> +	}
```suggestion
         var selectedRepoIDs *SelectedRepoIDs
	if secret.Visibility == vault.SELECTED_VISIBILITY {
		repositoryIds, err := g.retrieveRepositoriesIds(secret.Repositories)
		if err != nil {
			return err
		}
		selectedRepoIDs = repositoryIds
	} else {
	  selectedRepoIDs = []	
	}
	ghSecret := &github.EncryptedSecret{
			Name:                  secret.Name,
			KeyID:                 g.keyID,
			EncryptedValue:        encryptedSecret,
			Visibility:            secret.Visibility,
			SelectedRepositoryIDs: selectedRepoIDs,
		}

```
something like this, less duplication

2025-01-03 23:10 UTC, tsoetje commented on internal/github/github.go
> +	if variable.Visibility == vault.SELECTED_VISIBILITY {
same can be done here

2025-01-03 23:10 UTC, tsoetje commented on internal/vault/azure.go
> +		page, err := pager.NextPage(context.TODO())
why not use?
```suggestion
		page, err := pager.NextPage(context.Background())
```

2025-01-03 23:10 UTC, tsoetje commented on internal/vault/azure.go
> +			pullSecret, err := v.client.GetSecret(context.TODO(), secret.ID.Name(), secret.ID.Version(), &azsecrets.GetSecretOptions{})
```suggestion
			pullSecret, err := v.client.GetSecret(context.Background(), secret.ID.Name(), secret.ID.Version(), &azsecrets.GetSecretOptions{})
```
same

2025-01-06 08:34 UTC, tijmenstor commented on README.md
> +- `repositories` (string) **optional**: The repositories that the secret/variable should be visible to (comma-separated)
Defaults are descibed earlier in the document.

2025-01-06 08:39 UTC, tijmenstor commented on internal/github/github.go
> +	}
I think I tried this before, but because `visibility` is not `selected`, GH API does not expect `SelectedRepositoryIDs` at all. But let me verify

2025-01-06 08:49 UTC, tijmenstor commented on internal/github/github.go
> +	}
Found a different approach that works, great suggestion!

2025-01-06 08:50 UTC, tijmenstor commented on internal/vault/azure.go
> +		page, err := pager.NextPage(context.TODO())
Dove a bit into the functionality of these, will change to use `context.Background()`

2025-01-10 14:32 UTC, thijsvtol commented on .env.example
> +AZURE_CLIENT_ID="an-azure-client-id"
optional: managed identity instead/?

2025-01-10 14:32 UTC, thijsvtol commented on .github/workflows/ci-build.yaml
> +  GOLANG_VERSION: '1.23.3'
1.24 buddy

2025-01-10 14:35 UTC, thijsvtol commented on internal/github/github.go
> +	installationID int64
```suggestion
	appID          int16
	installationID int16
```

2025-01-10 14:38 UTC, thijsvtol commented on internal/github/github.go
> +	}
You can also build a function for validating types which returns feedback in the console

2025-01-10 14:43 UTC, thijsvtol approved these changes

2025-01-15 09:00 UTC, tijmenstor commented on .github/workflows/ci-build.yaml
> +  GOLANG_VERSION: '1.23.3'
Not released yet buddy

2025-01-15 09:00 UTC, tijmenstor commented on .env.example
> +AZURE_CLIENT_ID="an-azure-client-id"
Added a comment as TODO

2025-01-15 09:01 UTC, tijmenstor commented on internal/github/github.go
> +	installationID int64
Ah the underlying package expects `int64` as type

2025-01-15 09:19 UTC, merged